### ISSUE TITLE
PowerVC emty result list_images and list_networks (PowerVC 2.0.2) 

### ISSUE THREAD

**Issue by ALutz273** [ppc64le/devops-automation#22]
ansible-playbook  list_images.yml

PLAY [List available PowerVC Images] **************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [Retrieve list of all AIX images] ************************************************************************************************************************************************
ok: [localhost]

TASK [Print image list] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": []
}

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

 

ansible 2.9.24
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep  9 2021, 08:02:18) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

Openstack Cloud Ansilbe modules v1.6.0

**Comment by jwcroppe** [comment]
@jaywcarman - any thoughts on this?

**Comment by jaywcarman** [comment]
Hi @ALutz273! I just tested both `list_images.yml` and `list_networks.yml` locally and both worked. Here's my environment:
```
(venv) devops-automation|master|b654626 ✗|powervc$ ansible --version                                                                                                                                                                                          
ansible [core 2.12.2] 
  config file = /home/jwcarman/src/github.com/ppc64le/devops-automation/ansible/powervc/ansible.cfg
  configured module search path = ['/home/jwcarman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jwcarman/src/github.com/ppc64le/devops-automation/ansible/powervc/venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/jwcarman/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jwcarman/src/github.com/ppc64le/devops-automation/ansible/powervc/venv/bin/ansible
  python version = 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  jinja version = 3.0.3
  libyaml = True
(venv) devops-automation|master|b654626 ✗|powervc$ curl --cacert powervc.crt https://sles-bvt-vm6.pok.stglabs.ibm.com/powervc/version
{"version": "1.4.4.2"}
```

The first time I ran `ansible-playbook list_images.yml` I actually got an empty list as well! But then I realized that this sample playbook is setup to return _only_ AIX images (see [this comment in the source](https://github.com/ppc64le/devops-automation/blob/master/ansible/powervc/list_images.yml#L8)), and my test cluster has _only_ Linux images. Perhaps your cluster also doesn't have any AIX images?

Another suggestion is to use the [openstack cli client](https://docs.openstack.org/newton/user-guide/common/cli-install-openstack-command-line-clients.html) to see if you get similar results. Here's an example of `openstack image list` from my environment:
```
(venv) devops-automation|master|b654626 ✗|powervc$ openstack image list                                                              
+--------------------------------------+-----------------------+--------+
| ID                                   | Name                  | Status |
+--------------------------------------+-----------------------+--------+
| 0f19cf4c-4b91-4f3b-b0b1-4948992dd4aa | RHEL82_100Gb_Suraj    | active |
| 6dee68a4-9924-4489-968c-41269c55bb98 | RHEL83                | active |
| 2798216a-3926-4223-b168-3d493c7d1dd7 | SLES11_SP4            | active |
| fd343d6e-cbdf-4b07-9eb3-c0d0315fe770 | SLES15SP2-CI19.1-COLO | active |
| 23ad84eb-c131-4b4a-8a49-63a21de0d1b8 | SLES15SP2_COLO        | active |
+--------------------------------------+-----------------------+--------+
```

Hope this helps!

**Comment by ALutz273** [comment]
Hi @jaywcarman 

i use only linux images.
I remove the filter "os_distro: aix". After that i works fine. 
Thanks for the quick help! 👍
