### ISSUE TITLE
Error code 500 "user IBMid-xxxxxxx does not have any access authority"

### ISSUE THREAD

**Issue by kdixonIBM** [ppc64le/devops-automation#6]
I'm receiving the following message when executing the terraform plan:
Error: Error refreshing state: 2 errors occurred:
	* data.ibm_pi_network.power_networks: 1 error occurred:
	* data.ibm_pi_network.power_networks: data.ibm_pi_network.power_networks: {"code":500,"message":"user IBMid-xxxxxxx does not have any access authority"}

	* data.ibm_pi_image.power_images: 1 error occurred:
	* data.ibm_pi_image.power_images: data.ibm_pi_image.power_images: {"code":500,"message":"user IBMid-xxxxxxx does not have any access authority"}

I've checked all of the variables (Cloud API key, IaaS Classic API key, SSH, etc) and cannot find anything wrong. The user ID in the error message is for my personal account. This is an IBM internal account which I own. I have Adminstrator/Manager access across the entire account. I can successfully issue ibmcloud pi CLI commands to view, create, delete Power resources, and I can also do the same via the cloud Console. 

What should I be looking for to debug this access authority error message?

**Comment by jwcroppe** [comment]
@kdixonIBM Are you sure the API key that you created is associated with the internal account?  There's a drop-down in the upper right corner of the IBM Cloud GUI to select different accounts... I suspect the API key might have been created under your personal account and thus can't access resources created under the internal account?

**Comment by kdixonIBM** [comment]
I only have access to this one account.

**Comment by kdixonIBM** [comment]
I found the problem. The "cloud_instance_id" in variables.tf was incorrect. I was using the full CRN of the Power VS Service Instance. I changed it to what I understand to be the correct ID based on this link, and it resolved the problem. 
https://cloud.ibm.com/apidocs/power-cloud#authentication

**Comment by jwcroppe** [comment]
Great news @kdixonIBM - glad you were able to get this resolved!
